export const commonIconsActionsTypes = {
    'FETCH_COMMON_ICONS_USER_OPTIONS_START': 'FETCH_COMMON_ICONS_USER_OPTIONS_START',
    'FETCH_COMMON_ICONS_USER_OPTIONS_SUCCESS': 'FETCH_COMMON_ICONS_USER_OPTIONS_SUCCESS',
    'FETCH_COMMON_ICONS_USER_OPTIONS_FAILURE': 'FETCH_COMMON_ICONS_USER_OPTIONS_FAILURE',
    'SET_COMMON_ICON_TAB_SEARCH_VALUE': 'SET_COMMON_ICON_TAB_SEARCH_VALUE',
    'SET_COMMON_ICON_TAB_SELECT_VALUE': 'SET_COMMON_ICON_TAB_SELECT_VALUE'
}