export const favoriteIconsActionTypes = {
    'SET_CURRENT_USER_FAVORITE_FETCH_MAP': 'SET_CURRENT_USER_FAVORITE_FETCH_MAP',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_START': 'FETCH_CURRENT_USER_FAVORITE_ICONS_START',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_SUCCESS': 'FETCH_CURRENT_USER_FAVORITE_ICONS_SUCCESS',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_FAILURE': 'FETCH_CURRENT_USER_FAVORITE_ICONS_FAILURE'
};