export const favoriteIconsActionTypes = {
    'SET_CURRENT_USER_FAVORITE_FETCH_MAP': 'SET_CURRENT_USER_FAVORITE_FETCH_MAP',
    'SET_FAVORITE_TAB_SEARCH_VALUE': 'SET_FAVORITE_TAB_SEARCH_VALUE',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_START': 'FETCH_CURRENT_USER_FAVORITE_ICONS_START',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_SUCCESS': 'FETCH_CURRENT_USER_FAVORITE_ICONS_SUCCESS',
    'FETCH_CURRENT_USER_FAVORITE_ICONS_FAILURE': 'FETCH_CURRENT_USER_FAVORITE_ICONS_FAILURE'
};