export const generalIconsActionsTypes = {
    'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_START': 'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_START',
    'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_SUCCESS': 'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_SUCCESS',
    'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_FAILURE': 'FETCH_SEARCH_KEYWORD_AND_CATEGORY_LIST_FAILURE'
}