export const toastMessageActionTypes = {
    'RESET_TOAST_MESSAGE_STATE': 'RESET_TOAST_MESSAGE_STATE',
    'SHOW_SUCCESS_TOAST_MESSAGE': 'SHOW_SUCCESS_TOAST_MESSAGE',
    'SHOW_FAILURE_TOAST_MESSAGE': 'SHOW_FAILURE_TOAST_MESSAGE'
}