export const authActionTypes = {
    'USER_LOGIN_START': 'USER_LOGIN_START',
    'USER_LOGIN_SUCCESS': 'USER_LOGIN_SUCCESS',
    'USER_LOGIN_FAILURE': 'USER_LOGIN_FAILURE',
    'SIGN_UP_START': 'SIGN_UP_START',
    'SIGN_UP_SUCCESS': 'SIGN_UP_SUCCESS',
    'SIGN_UP_FAILURE': 'SIGN_UP_FAILURE',
    'SEND_PASSWORD_RESET_LINK_START': 'SEND_PASSWORD_RESET_LINK_START',
    'SEND_PASSWORD_RESET_LINK_SUCCESS': 'SEND_PASSWORD_RESET_LINK_SUCCESS',
    'SEND_PASSWORD_RESET_LINK_FAILURE': 'SEND_PASSWORD_RESET_LINK_FAILURE',
    'UPDATE_NEW_PASSWORD_START': 'UPDATE_NEW_PASSWORD_START',
    'UPDATE_NEW_PASSWORD_SUCCESS': 'UPDATE_NEW_PASSWORD_SUCCESS',
    'UPDATE_NEW_PASSWORD_FAILURE': 'UPDATE_NEW_PASSWORD_FAILURE',
    'CLEAR_AUTH_ERROR': 'CLEAR_AUTH_ERROR'
} 