export const uploadIconsActionTypes = {
    'OPEN_UPLOAD_MODAL': 'OPEN_UPLOAD_MODAL',
    'CLOSE_UPLOAD_MODAL': 'CLOSE_UPLOAD_MODAL',
    'SET_UPLOADED_COMMON_ICONS': 'SET_UPLOADED_COMMON_ICONS',
    'CHANGE_UPLOAD_MODAL_VIEW': 'CHANGE_UPLOAD_MODAL_VIEW',
    'CHANGE_CLASSIFICATION_FOR_ALL_UPLOADED_ICONS': 'CHANGE_CLASSIFICATION_FOR_ALL_UPLOADED_ICONS',
    'DELETE_UPLOADED_COMMON_ICON': 'DELETE_UPLOADED_COMMON_ICON',
    'CHANGE_UPLOAD_ICON_NAME': 'CHANGE_UPLOAD_ICON_NAME',
    'CHANGE_UPLOAD_ICON_CLASSIFICATION': 'CHANGE_UPLOAD_ICON_CLASSIFICATION',
    'ADD_NEW_CLASSIFICATION': 'ADD_NEW_CLASSIFICATION',
    'CHANGE_COMMON_ROOT_TAGS': 'CHANGE_COMMON_ROOT_TAGS',
};