export const uploadIconsActionTypes = {
    'OPEN_UPLOAD_MODAL': 'OPEN_UPLOAD_MODAL',
    'CLOSE_UPLOAD_MODAL_VIEW': 'CLOSE_UPLOAD_MODAL_VIEW',
    'SET_UPLOADED_COMMON_ICONS': 'SET_UPLOADED_COMMON_ICONS',
    'SET_UPLOAD_MODAL_VIEW': 'SET_UPLOAD_MODAL_VIEW',
    'CHANGE_CLASSIFICATION_FOR_ALL_ICONS': 'CHANGE_CLASSIFICATION_FOR_ALL_ICONS',
    'DELETE_UPLOADED_COMMON_ICON': 'DELETE_UPLOADED_COMMON_ICON',
    'CHANGE_UPLOAD_ICON_NAME': 'CHANGE_UPLOAD_ICON_NAME',
    'CHANGE_UPLOAD_ICON_CLASSIFICATION': 'CHANGE_UPLOAD_ICON_CLASSIFICATION'
};