export const uploadIconsActionTypes = {
    'OPEN_UPLOAD_MODAL_VIEW': 'OPEN_UPLOAD_MODAL_VIEW',
    'CLOSE_UPLOAD_MODAL_VIEW': 'CLOSE_UPLOAD_MODAL_VIEW',
    'SET_UPLOADED_COMMON_ICONS': 'SET_UPLOADED_COMMON_ICONS',
    'SET_UPLOAD_MODAL_VIEW': 'SET_UPLOAD_MODAL_VIEW',
    'SET_DEFAULT_CLASSIFICATION': 'SET_DEFAULT_CLASSIFICATION',
    'DELETE_UPLOADED_COMMON_ICON': 'DELETE_UPLOADED_COMMON_ICON',
    'EDIT_UPLOAD_ICON_NAME': 'EDIT_UPLOAD_ICON_NAME',
    'EDIT_UPLOAD_ICON_CLASSIFICATION': 'EDIT_UPLOAD_ICON_CLASSIFICATION'
};