export const userActionTypes = {
    'USER_AUTH_SUCCESS': 'USER_AUTH_SUCCESS',
    'CHECK_USER_PERSISTANCE': 'CHECK_USER_PERSISTANCE',
    'CHECK_USER_PERSISTANCE_COMPLETED': 'CHECK_USER_PERSISTANCE_COMPLETED',
    'USER_SIGN_OUT_START': 'USER_SIGN_OUT_START',
    'USER_SIGN_OUT_SUCCESS': 'USER_SIGN_OUT_SUCCESS',
    'USER_SIGN_OUT_FAILURE': 'USER_SIGN_OUT_FAILURE'
};