export const userActionTypes = {
    'STORE_CURRENT_USER': 'STORE_CURRENT_USER',
    "GET_CURRENT_USER_INFO_START": 'GET_CURRENT_USER_INFO_START',
    "GET_CURRENT_USER_INFO_SUCCESS": 'GET_CURRENT_USER_INFO_SUCCESS',
    "GET_CURRENT_USER_INFO_FAILURE": 'GET_CURRENT_USER_INFO_FAILURE',
    'CHECK_USER_PERSISTANCE_START': 'CHECK_USER_PERSISTANCE_START',
    'CHECK_USER_PERSISTANCE_COMPLETED': 'CHECK_USER_PERSISTANCE_COMPLETED',
    'USER_SIGN_OUT_START': 'USER_SIGN_OUT_START',
    'USER_SIGN_OUT_SUCCESS': 'USER_SIGN_OUT_SUCCESS',
    'USER_SIGN_OUT_FAILURE': 'USER_SIGN_OUT_FAILURE',
};