export const projectIconsActionTypes = {
    'FETCH_PROJECT_ICONS_USER_OPTIONS_START': 'FETCH_PROJECT_ICONS_USER_OPTIONS_START',
    'FETCH_PROJECT_ICONS_USER_OPTIONS_SUCCESS': 'FETCH_PROJECT_ICONS_USER_OPTIONS_SUCCESS',
    'FETCH_PROJECT_ICONS_USER_OPTIONS_FAILURE': 'FETCH_PROJECT_ICONS_USER_OPTIONS_FAILURE',
    'FETCH_PROJECT_ICONS_FROM_DB_START': 'FETCH_PROJECT_ICONS_FROM_DB_START',
    'FETCH_PROJECT_ICONS_FROM_DB_SUCCESS': 'FETCH_PROJECT_ICONS_FROM_DB_SUCCESS',
    'FETCH_PROJECT_ICONS_FROM_DB_FAILURE': 'FETCH_PROJECT_ICONS_FROM_DB_FAILURE',
    'SET_PROJECT_ICONS_TAB_SEARCH_VALUE': 'SET_PROJECT_ICONS_TAB_SEARCH_VALUE',
    'SET_PROJECT_ICONS_TAB_SELECT_VALUE': 'SET_PROJECT_ICONS_TAB_SELECT_VALUE',
    'SET_PROJECT_ICONS_PAGINATION': 'SET_PROJECT_ICONS_PAGINATION'
};