export const editIconActionTypes = {
    'EDIT_USER_SELECTED_ICON': 'EDIT_USER_SELECTED_ICON',
    'CHANGE_ICON_DOWNLOAD_FORMAT': 'CHANGE_ICON_DOWNLOAD_FORMAT',
    'CHANGE_STANDARD_DOWNLOAD_SIZE': 'CHANGE_STANDARD_DOWNLOAD_SIZE',
    'CHANGE_CUSTOM_DOWNLOAD_SIZE': 'CHANGE_CUSTOM_DOWNLOAD_SIZE',
    'CHANGE_USER_SELECTED_COLOR': 'CHANGE_USER_SELECTED_COLOR',
    'ICON_DOWNLOAD_START': 'ICON_DOWNLOAD_START',
    'ICON_DOWNLOAD_SUCCESS': 'ICON_DOWNLOAD_SUCCESS',
    'ICON_DOWNLOAD_FAILURE': 'ICON_DOWNLOAD_FAILURE',
    'CLOSE_EDIT_ICON_MODAL': 'CLOSE_EDIT_ICON_MODAL'
};