export const editIconActionTypes = {
    'EDIT_USER_SELECTED_ICON': 'EDIT_USER_SELECTED_ICON',
    'CHANGE_ICON_DOWNLOAD_FORMAT': 'CHANGE_ICON_DOWNLOAD_FORMAT',
    'CLOSE_EDIT_ICON_MODAL': 'CLOSE_EDIT_ICON_MODAL'
};