export const signInSignUpActionTypes = {
    'SIGN_IN_VIEW_SELECTED': 'SIGN_IN_VIEW_SELECTED',
    'SIGN_UP_VIEW_SELECTED': 'SIGN_UP_VIEW_SELECTED',
    'USER_LOGIN_VIEW_SELECTED': 'USER_LOGIN_VIEW_SELECTED',
    'FORGOT_PASSWORD_VIEW_SELECTED': 'FORGOT_PASSWORD_VIEW_SELECTED',
    'USER_LOGIN_START': 'USER_LOGIN_START',
    'USER_LOGIN_SUCCESS': 'USER_LOGIN_SUCCESS',
    'USER_LOGIN_FAILURE': 'USER_LOGIN_FAILURE',
    'CLEAR_SIGN_IN_ERROR': 'CLEAR_SIGN_IN_ERROR',
    'SIGN_UP_START': 'SIGN_UP_START',
    'SIGN_UP_SUCCESS': 'SIGN_UP_SUCCESS',
    'SIGN_UP_FAILURE': 'SIGN_UP_FAILURE',
    'CLEAR_SIGN_UP_ERROR': 'CLEAR_SIGN_UP_ERROR',
    'SEND_PASSWORD_RESET_LINK_START': 'SEND_PASSWORD_RESET_LINK_START',
    'SEND_PASSWORD_RESET_LINK_SUCCESS': 'SEND_PASSWORD_RESET_LINK_SUCCESS',
    'SEND_PASSWORD_RESET_LINK_FAILURE': 'SEND_PASSWORD_RESET_LINK_FAILURE',

} 