export const signInSignUpActionTypes = {
    'SIGN_IN_VIEW_SELECTED': 'SIGN_IN_VIEW_SELECTED',
    'SIGN_UP_VIEW_SELECTED': 'SIGN_UP_VIEW_SELECTED',
    'USER_LOGIN_VIEW_SELECTED': 'USER_LOGIN_VIEW_SELECTED',
    'FORGOT_PASSWORD_VIEW_SELECTED': 'FORGOT_PASSWORD_VIEW_SELECTED',
    'SIGN_UP_START': 'SIGN_UP_START',
    'SIGN_UP_SUCCESS': 'SIGN_UP_SUCCESS',
    'SIGN_UP_FAILURE': 'SIGN_UP_FAILURE',
    'CLEAR_SIGN_UP_ERROR': 'CLEAR_SIGN_UP_ERROR',
    'SET_LOADING_STATUS_FOR_SIGNIN_SIGNUP': 'SET_LOADING_STATUS_FOR_SIGNIN_SIGNUP',
    'USER_LOGIN_START': 'USER_LOGIN_START',
    'SEND_PASSWORD_RESET_LINK': 'SEND_PASSWORD_RESET_LINK'
} 