export const signInSignUpActionTypes = {
    'SIGN_IN_VIEW_SELECTED': 'SIGN_IN_VIEW_SELECTED',
    'SIGN_UP_VIEW_SELECTED': 'SIGN_UP_VIEW_SELECTED',
    'USER_LOGIN_VIEW_SELECTED':'USER_LOGIN_VIEW_SELECTED',
    'FORGOT_PASSWORD_VIEW_SELECTED':'FORGOT_PASSWORD_VIEW_SELECTED'
} 